# Generated by Django 5.0.4 on 2024-04-30 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='imge',
            field=models.ImageField(default=datetime.datetime(2024, 4, 30, 22, 32, 54, 612371, tzinfo=datetime.timezone.utc), upload_to='carreras/images'),
            preserve_default=False,
        ),
    ]
